config/routes.rb
Healthcare::Application.routes.draw do
  resources :medical_providers

  resources :providers

  resources :employees

  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/medical_provider.rb
class MedicalProvider < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    
      if @employee.save
        redirect_to @employee, notice: 'Employee was successfully created.' 
        
      else
        render action: 'new' 
        
      end
    
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    
      if @employee.update(employee_params)
       redirect_to @employee, notice: 'Employee was successfully updated.' 
        
      else
       render action: 'edit' 
        
      end
    
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    
      redirect_to employees_url 
    
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:FirstName, :LastName, :EmployeeId, :EmailAddress, :Department)
    end
end

app/controllers/medical_providers_controller.rb
class MedicalProvidersController < ApplicationController
  before_action :set_medical_provider, only: [:show, :edit, :update, :destroy]

  # GET /medical_providers
  # GET /medical_providers.json
  def index
    @medical_providers = MedicalProvider.all
  end

  # GET /medical_providers/1
  # GET /medical_providers/1.json
  def show
  end

  # GET /medical_providers/new
  def new
    @medical_provider = MedicalProvider.new
  end

  # GET /medical_providers/1/edit
  def edit
  end

  # POST /medical_providers
  # POST /medical_providers.json
  def create
    @medical_provider = MedicalProvider.new(medical_provider_params)

    
      if @medical_provider.save
         redirect_to @medical_provider, notice: "#{@medical_provider.Specialty} was successfully created."
        
      else
          render action: 'new' 
         
      end
    
  end

  # PATCH/PUT /medical_providers/1
  # PATCH/PUT /medical_providers/1.json
  def update
    
      if @medical_provider.update(medical_provider_params)
        redirect_to @medical_provider, notice: "#{@medical_provider.Specialty} was successfully updated."
        
      else
        render action: 'edit' 
       
      end
    
  end

  # DELETE /medical_providers/1
  # DELETE /medical_providers/1.json
  def destroy
    @medical_provider.destroy
    
       redirect_to medical_providers_url 
     
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_provider
      @medical_provider = MedicalProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medical_provider_params
      params.require(:medical_provider).permit(:Specialty, :string, :street, :City, :Zip)
    end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    
      if @provider.save
         redirect_to @provider, notice: 'Provider was successfully created.' 
        
      else
        render action: 'new' 
        
      end
    
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
  
      if @provider.update(provider_params)
       redirect_to @provider, notice: 'Provider was successfully updated.' 
        
      else
        render action: 'edit' 
        
      end
    
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    
      redirect_to providers_url 
      
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:Name, :Street, :City, :State, :Zip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/medical_providers_helper.rb
module MedicalProvidersHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :FirstName %><br>
    <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br>
    <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label :EmployeeId %><br>
    <%= f.text_field :EmployeeId %>
  </div>
  <div class="field">
    <%= f.label :EmailAddress %><br>
    <%= f.text_field :EmailAddress %>
  </div>
  <div class="field">
    <%= f.label :Department %><br>
    <%= f.text_field :Department %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Employeeid</th>
      <th>Emailaddress</th>
      <th>Department</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.FirstName %></td>
        <td><%= employee.LastName %></td>
        <td><%= employee.EmployeeId %></td>
        <td><%= employee.EmailAddress %></td>
        <td><%= employee.Department %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.FirstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.LastName %>
</p>

<p>
  <strong>Employeeid:</strong>
  <%= @employee.EmployeeId %>
</p>

<p>
  <strong>Emailaddress:</strong>
  <%= @employee.EmailAddress %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.Department %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Healthcare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medical_providers/_form.html.erb
<%= form_for(@medical_provider) do |f| %>
  <% if @medical_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medical_provider.errors.count, "error") %> prohibited this medical_provider from being saved:</h2>

      <ul>
      <% @medical_provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Specialty %><br>
    <%= f.text_field :Specialty %>
  </div>
  
  
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :Zip %><br>
    <%= f.text_field :Zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medical_providers/edit.html.erb
<h1>Editing medical_provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @medical_provider %> |
<%= link_to 'Back', medical_providers_path %>

app/views/medical_providers/index.html.erb
<h1>Listing medical_providers</h1>

<table>
  <thead>
    <tr>
      <th>Specialty</th>
      <th>String</th>
      <th>Street</th>
      <th>City</th>
      <th>Zip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_providers.each do |medical_provider| %>
      <tr>
        <td><%= medical_provider.Specialty %></td>
        
        <td><%= medical_provider.street %></td>
        <td><%= medical_provider.City %></td>
        <td><%= medical_provider.Zip %></td>
        <td><%= link_to 'Show', medical_provider %></td>
        <td><%= link_to 'Edit', edit_medical_provider_path(medical_provider) %></td>
        <td><%= link_to 'Destroy', medical_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medical provider', new_medical_provider_path %>

app/views/medical_providers/new.html.erb
<h1>New medical_provider</h1>

<%= render 'form' %>

<%= link_to 'Back', medical_providers_path %>

app/views/medical_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Specialty:</strong>
  <%= @medical_provider.Specialty %>
</p>



<p>
  <strong>Street:</strong>
  <%= @medical_provider.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @medical_provider.City %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @medical_provider.Zip %>
</p>

<%= link_to 'Edit', edit_medical_provider_path(@medical_provider) %> |
<%= link_to 'Back', medical_providers_path %>

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Street %><br>
    <%= f.text_field :Street %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :State %><br>
    <%= f.text_field :State %>
  </div>
  <div class="field">
    <%= f.label :Zip %><br>
    <%= f.text_field :Zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.Name %></td>
        <td><%= provider.Street %></td>
        <td><%= provider.City %></td>
        <td><%= provider.State %></td>
        <td><%= provider.Zip %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.Name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @provider.Street %>
</p>

<p>
  <strong>City:</strong>
  <%= @provider.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @provider.State %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @provider.Zip %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>